### ISSUE TITLE
p2p sending incorrect packets to bootstrap node

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/p2p#1107] opened 2018-10-26 17:32 UTC
* **What's your Operating System?**
Debian, vagrant box.  
<pre>
root@subutai:/tmp# uname -a
Linux subutai 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
</pre>

*  **Describe your problem and steps to reproduce it**
Started to happen without upgrading ( version subutai-p2p_8.0.1+20181009061047_amd64.deb ), but continues now with  latest ( subutai-p2p_8.0.1+20181026081036_amd64.deb ). I can't say what caused, since was working perfectly.

* **Show output of `p2p debug`**
<pre>
root@subutai:~# p2p debug
Version: 8.0.1+20181026081036 Build: 8.0.1
Uptime: 0 h 23 m 49 s
Number of gouroutines: 11
PMTU: Disabled
Bootstrap nodes information:
  62.138.0.225:6881 Rx: 1253 Tx: 0 Version: 8.0.2 Packet version: 20005
Instances information:

root@subutai:~# 
</pre>

* **Attach p2p log or sensible part of it**
I tcpdump'ed the traffic between my box and boostrap node, it seems  only the server is correct sending packets, my box always send incorrect packets checksums:
<pre>
root@subutai:~# tcpdump -i enp0s8 -U -vv 'port 47104'
17:15:59.064976 IP (tos 0x0, ttl 64, id 12790, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xabbc), seq 2322450052:2322450063, ack 3207774107, win 229, options [nop,nop,TS val 171908 ecr 465285038], length 11
17:15:59.266130 IP (tos 0x0, ttl 48, id 40503, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xc785 (correct), seq 1:27, ack 11, win 227, options [nop,nop,TS val 465292537 ecr 171908], length 26
17:15:59.266199 IP (tos 0x0, ttl 64, id 12791, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x4a88), seq 11, ack 27, win 229, options [nop,nop,TS val 171958 ecr 465292537], length 0
17:16:29.104630 IP (tos 0x0, ttl 64, id 12792, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x70f6), seq 11:22, ack 27, win 229, options [nop,nop,TS val 179418 ecr 465292537], length 11
17:16:29.307557 IP (tos 0x0, ttl 48, id 40504, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x8cb0 (correct), seq 27:53, ack 22, win 227, options [nop,nop,TS val 465300051 ecr 179418], length 26
17:16:29.307595 IP (tos 0x0, ttl 64, id 12793, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x0fb3), seq 22, ack 53, win 229, options [nop,nop,TS val 179468 ecr 465300051], length 0
17:16:59.179536 IP (tos 0x0, ttl 64, id 12794, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x3619), seq 22:33, ack 53, win 229, options [nop,nop,TS val 186936 ecr 465300051], length 11
17:16:59.380530 IP (tos 0x0, ttl 48, id 40505, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x51cc (correct), seq 53:79, ack 33, win 227, options [nop,nop,TS val 465307572 ecr 186936], length 26
17:16:59.380550 IP (tos 0x0, ttl 64, id 12795, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xd4ce), seq 33, ack 79, win 229, options [nop,nop,TS val 186986 ecr 465307572], length 0
17:17:29.221191 IP (tos 0x0, ttl 64, id 12796, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xfb3b), seq 33:44, ack 79, win 229, options [nop,nop,TS val 194447 ecr 465307572], length 11
17:17:29.422712 IP (tos 0x0, ttl 48, id 40506, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x16fa (correct), seq 79:105, ack 44, win 227, options [nop,nop,TS val 465315082 ecr 194447], length 26
17:17:29.422748 IP (tos 0x0, ttl 64, id 12797, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x99fc), seq 44, ack 105, win 229, options [nop,nop,TS val 194497 ecr 465315082], length 0
17:17:59.285343 IP (tos 0x0, ttl 64, id 12798, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xc064), seq 44:55, ack 105, win 229, options [nop,nop,TS val 201963 ecr 465315082], length 11
17:17:59.486639 IP (tos 0x0, ttl 48, id 40507, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xdc1d (correct), seq 105:131, ack 55, win 227, options [nop,nop,TS val 465322597 ecr 201963], length 26
17:17:59.486698 IP (tos 0x0, ttl 64, id 12799, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x5f20), seq 55, ack 131, win 229, options [nop,nop,TS val 202013 ecr 465322597], length 0
17:18:29.372416 IP (tos 0x0, ttl 64, id 12800, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x8583), seq 55:66, ack 131, win 229, options [nop,nop,TS val 209484 ecr 465322597], length 11
17:18:29.573196 IP (tos 0x0, ttl 48, id 40508, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xa135 (correct), seq 131:157, ack 66, win 227, options [nop,nop,TS val 465330119 ecr 209484], length 26
17:18:29.573250 IP (tos 0x0, ttl 64, id 12801, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x2437), seq 66, ack 157, win 229, options [nop,nop,TS val 209535 ecr 465330119], length 0
17:18:59.374662 IP (tos 0x0, ttl 64, id 12802, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x4aaf), seq 66:77, ack 157, win 229, options [nop,nop,TS val 216985 ecr 465330119], length 11
17:18:59.578735 IP (tos 0x0, ttl 48, id 40509, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x6677 (correct), seq 157:183, ack 77, win 227, options [nop,nop,TS val 465337619 ecr 216985], length 26
17:18:59.578772 IP (tos 0x0, ttl 64, id 12803, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xe978), seq 77, ack 183, win 229, options [nop,nop,TS val 217036 ecr 465337619], length 0
17:19:29.418920 IP (tos 0x0, ttl 64, id 12804, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x0fe7), seq 77:88, ack 183, win 229, options [nop,nop,TS val 224496 ecr 465337619], length 11
17:19:29.620410 IP (tos 0x0, ttl 48, id 40510, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x2ba5 (correct), seq 183:209, ack 88, win 227, options [nop,nop,TS val 465345129 ecr 224496], length 26
17:19:29.620469 IP (tos 0x0, ttl 64, id 12805, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xaea7), seq 88, ack 209, win 229, options [nop,nop,TS val 224546 ecr 465345129], length 0
17:19:59.516238 IP (tos 0x0, ttl 64, id 12806, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xd507), seq 88:99, ack 209, win 229, options [nop,nop,TS val 232020 ecr 465345129], length 11
17:19:59.717410 IP (tos 0x0, ttl 48, id 40511, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xf0b7 (correct), seq 209:235, ack 99, win 227, options [nop,nop,TS val 465352653 ecr 232020], length 26
17:19:59.717496 IP (tos 0x0, ttl 64, id 12807, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x73b9), seq 99, ack 235, win 229, options [nop,nop,TS val 232071 ecr 465352653], length 0
17:20:29.547065 IP (tos 0x0, ttl 64, id 12808, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x9a2a), seq 99:110, ack 235, win 229, options [nop,nop,TS val 239528 ecr 465352653], length 11
17:20:29.748230 IP (tos 0x0, ttl 48, id 40512, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xb5eb (correct), seq 235:261, ack 110, win 227, options [nop,nop,TS val 465360160 ecr 239528], length 26
17:20:29.748294 IP (tos 0x0, ttl 64, id 12809, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x38ee), seq 110, ack 261, win 229, options [nop,nop,TS val 239578 ecr 465360160], length 0
17:20:59.621510 IP (tos 0x0, ttl 64, id 12810, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x5f53), seq 110:121, ack 261, win 229, options [nop,nop,TS val 247047 ecr 465360160], length 11
17:20:59.831980 IP (tos 0x0, ttl 48, id 40513, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x7b07 (correct), seq 261:287, ack 121, win 227, options [nop,nop,TS val 465367680 ecr 247047], length 26
17:20:59.832020 IP (tos 0x0, ttl 64, id 12811, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xfe07), seq 121, ack 287, win 229, options [nop,nop,TS val 247099 ecr 465367680], length 0
17:21:29.667588 IP (tos 0x0, ttl 64, id 12812, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x2477), seq 121:132, ack 287, win 229, options [nop,nop,TS val 254558 ecr 465367680], length 11
17:21:29.877167 IP (tos 0x0, ttl 48, id 40514, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x4032 (correct), seq 287:313, ack 132, win 227, options [nop,nop,TS val 465375193 ecr 254558], length 26
17:21:29.877278 IP (tos 0x0, ttl 64, id 12813, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xc331), seq 132, ack 313, win 229, options [nop,nop,TS val 254611 ecr 465375193], length 0
17:21:59.697536 IP (tos 0x0, ttl 64, id 12814, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xe9a4), seq 132:143, ack 313, win 229, options [nop,nop,TS val 262066 ecr 465375193], length 11
17:21:59.901744 IP (tos 0x0, ttl 48, id 40515, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x0564 (correct), seq 313:339, ack 143, win 227, options [nop,nop,TS val 465382702 ecr 262066], length 26
17:21:59.901801 IP (tos 0x0, ttl 64, id 12815, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x8865), seq 143, ack 339, win 229, options [nop,nop,TS val 262117 ecr 465382702], length 0
17:22:29.745906 IP (tos 0x0, ttl 64, id 12816, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xaed2), seq 143:154, ack 339, win 229, options [nop,nop,TS val 269578 ecr 465382702], length 11
17:22:29.946585 IP (tos 0x0, ttl 48, id 40516, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xca8f (correct), seq 339:365, ack 154, win 227, options [nop,nop,TS val 465390213 ecr 269578], length 26
17:22:29.946616 IP (tos 0x0, ttl 64, id 12817, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x4d92), seq 154, ack 365, win 229, options [nop,nop,TS val 269628 ecr 465390213], length 0
17:22:59.816485 IP (tos 0x0, ttl 64, id 12818, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x73f9), seq 154:165, ack 365, win 229, options [nop,nop,TS val 277095 ecr 465390213], length 11
17:23:00.017242 IP (tos 0x0, ttl 48, id 40517, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x8fb0 (correct), seq 365:391, ack 165, win 227, options [nop,nop,TS val 465397730 ecr 277095], length 26
17:23:00.017283 IP (tos 0x0, ttl 64, id 12819, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x12b2), seq 165, ack 391, win 229, options [nop,nop,TS val 277146 ecr 465397730], length 0
17:23:29.870440 IP (tos 0x0, ttl 64, id 12820, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x391d), seq 165:176, ack 391, win 229, options [nop,nop,TS val 284609 ecr 465397730], length 11
17:23:30.071287 IP (tos 0x0, ttl 48, id 40518, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x54d8 (correct), seq 391:417, ack 176, win 227, options [nop,nop,TS val 465405243 ecr 284609], length 26
17:23:30.071405 IP (tos 0x0, ttl 64, id 12821, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0xd7da), seq 176, ack 417, win 229, options [nop,nop,TS val 284659 ecr 465405243], length 0
17:23:59.942960 IP (tos 0x0, ttl 64, id 12822, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xfe40), seq 176:187, ack 417, win 229, options [nop,nop,TS val 292127 ecr 465405243], length 11
17:24:00.143736 IP (tos 0x0, ttl 48, id 40519, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0x19f8 (correct), seq 417:443, ack 187, win 227, options [nop,nop,TS val 465412760 ecr 292127], length 26
17:24:00.143813 IP (tos 0x0, ttl 64, id 12823, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x9cfa), seq 187, ack 443, win 229, options [nop,nop,TS val 292177 ecr 465412760], length 0
17:24:29.945121 IP (tos 0x0, ttl 64, id 12824, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0xc371), seq 187:198, ack 443, win 229, options [nop,nop,TS val 299628 ecr 465412760], length 11
17:24:30.145997 IP (tos 0x0, ttl 48, id 40520, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xdf39 (correct), seq 443:469, ack 198, win 227, options [nop,nop,TS val 465420260 ecr 299628], length 26
17:24:30.146029 IP (tos 0x0, ttl 64, id 12825, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x623c), seq 198, ack 469, win 229, options [nop,nop,TS val 299678 ecr 465420260], length 0
17:24:59.978158 IP (tos 0x0, ttl 64, id 12826, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.], cksum 0x004d (incorrect -> 0x88ac), seq 198:209, ack 469, win 229, options [nop,nop,TS val 307136 ecr 465420260], length 11
17:25:00.179621 IP (tos 0x0, ttl 48, id 40521, offset 0, flags [DF], proto TCP (6), length 78)
    prod-bazaar-eu-1.s.optdyn.com.6881 > 192.168.0.8.47104: Flags [P.], cksum 0xa46d (correct), seq 469:495, ack 209, win 227, options [nop,nop,TS val 465427767 ecr 307136], length 26
17:25:00.179701 IP (tos 0x0, ttl 64, id 12827, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [.], cksum 0x0042 (incorrect -> 0x2770), seq 209, ack 495, win 229, options [nop,nop,TS val 307186 ecr 465427767], length 0
17:25:29.984434 IP (tos 0x0, ttl 64, id 12828, offset 0, flags [DF], proto TCP (6), length 63)
    192.168.0.8.47104 > prod-bazaar-eu-1.s.optdyn.com.6881: Flags [P.],
</pre>

**Attached goes the fix-it-mike** script that gather other informations, thks folks :) !
[p2p-Linux-2018-10-26-17_14_39.tar.gz](https://github.com/subutai-io/p2p/files/2520197/p2p-Linux-2018-10-26-17_14_39.tar.gz)

**Comment by crioto** [comment] 2018-10-27 05:07
Thank you for detailed report. This is reproducable and going to be fixed in the upcoming release.

**Comment by crioto** [comment] 2018-10-29 06:49
Hello @marcoarthur 
I've investigated reported behavior and found that these incorrect checksums are happening due to network offload made by operating system on network layer. We can't do anything about it. You can use `ethtool` to disable offloading to see, that incorrect checksum doesn't appear anymore: 
`ethtool --offload  enp0s8  rx off  tx off`
(rerun command with `on` to get it back)

From your logs I can see that your dump file got borked. We've an issue about this (#1076) and it's fixed and being tested right now. We're planning to release p2p with this fix at Friday. However, you need to restore your p2p swarms manually. If you need assistance on how to do that, please, ping me on slack (`@mike`) at  https://slack.subutai.io/

Thank you,
Mike

**Closed by crioto** 2018-10-29 06:49 UTC
Labels: bug

**Comment by marcoarthur** [comment] 2018-10-30 13:32
Thanks, @crioto . I'll be waiting for your instructions on how to restore manually my p2p swarms. I could help you in the effort to write down the procedure on a Wiki page, after learn how to do it :)
