### ISSUE TITLE
P2P switches on Mac

### ISSUE THREAD

**Issue by TerGunter** [subutai-io/p2p#980] opened 2018-06-04 03:27 UTC
We got P2P switches which was tested on Mac OS
Ping to containers shows us packets loss to 20-80%
[output.txt](https://github.com/subutai-io/p2p/files/2066758/output.txt)
[-.txt](https://github.com/subutai-io/p2p/files/2066759/-.txt)

**Comment by crioto** [comment] 2018-07-30 10:33
Duplicate of #778

**Closed by crioto** 2018-07-30 10:33 UTC
Labels: Mac, bug, critical
