### ISSUE TITLE
removing (moving to trash) p2p from applications does not  delete p2p completely from computer.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/p2p#804] opened 2018-04-09 06:05 UTC
MacOS

I moved p2p to trash from application list but p2p debug still gives some output.

![screen shot 2018-04-09 at 12 03 21](https://user-images.githubusercontent.com/31571523/38481734-0e524460-3bee-11e8-9334-5e40a615ce44.png)
in above screenshot, you'll see that there is no subutai p2p file in the list.

p2p debug:
```
Shahris-Air:~ shahrizadakarasulu$ p2p debug
Version: 6.3.0-master Build: 6.2.20-211-g125807f
Uptime: 0 h 18 m 56 s
Number of gouroutines: 41
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 451102 Tx: 105273
Instances information:
Bootstrap nodes:
Hash: swarm-ed2c6db0-9d9a-444a-a08f-c48cccd1562a
ID: 390cbb65-3bb9-11e8-8303-060555473160
UDP Port: 59359
Network interfaces: 192.168.66.70 
P2P Interface tap1, HW Addr: 06:3e:42:b2:55:cc, IP: 10.39.91.245
Proxies: 13.250.117.166:40622/20016 54.183.200.212:40622/20016 52.58.220.11:40622/20002 35.159.10.202:40622/20002 54.233.167.241:40622/20016 
Peers:
	--- aba95ca2-3bb8-11e8-8926-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.39.91.1 06:5a:2e:38:e1:9a
	Endpoint: 62.138.0.36:42105
	All Endpoints: 62.138.0.36:42105 54.233.167.241:20044 13.250.117.166:20046 52.58.220.11:20044 35.159.10.202:20045 54.183.200.212:20043 
	Endpoints pool: 62.138.0.36:42105 172.26.154.252:42105 10.10.10.254:42105 172.20.37.252:42105 172.28.218.250:42105 172.28.216.251:42105 172.23.20.252:42105 172.22.53.252:42105 172.29.219.252:42105 172.20.152.251:42105 172.29.78.251:42105 172.18.221.246:42105 172.28.190.252:42105 52.58.220.11:20044 35.159.10.202:20045 54.183.200.212:20043 13.250.117.166:20046 54.233.167.241:20044 
	--- End of aba95ca2-3bb8-11e8-8926-060555473160 ---
Bootstrap nodes:
Hash: swarm-8ab9ca9e-d6b4-43a0-8b2f-7e7db4f9d840
ID: 43398344-3bb9-11e8-8316-060555473160
UDP Port: 64731
Network interfaces: 192.168.66.70 
P2P Interface tap2, HW Addr: 06:61:e8:dc:97:4a, IP: 10.214.13.245
Proxies: 35.159.10.202:40622/20019 54.233.167.241:40622/20023 13.250.117.166:40622/20023 54.183.200.212:40622/20023 52.58.220.11:40622/20019 
Peers:
	--- aa996d7c-3bb8-11e8-8cef-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.214.13.1 06:78:bc:92:38:55
	Endpoint: 62.138.0.36:51684
	All Endpoints: 62.138.0.36:51684 13.250.117.166:20019 52.58.220.11:20020 35.159.10.202:20020 54.233.167.241:20019 
	Endpoints pool: 62.138.0.36:51684 172.26.154.252:51684 10.10.10.254:51684 172.20.37.252:51684 172.28.218.250:51684 172.28.216.251:51684 172.23.20.252:51684 172.22.53.252:51684 172.29.219.252:51684 172.20.152.251:51684 172.29.78.251:51684 172.18.221.246:51684 172.28.190.252:51684 52.58.220.11:20020 35.159.10.202:20020 54.183.200.212:20019 54.233.167.241:20019 13.250.117.166:20019 
	--- End of aa996d7c-3bb8-11e8-8cef-060555473160 ---
Bootstrap nodes:
Hash: swarm-ab733af0-ddb2-4635-b4d5-63a174132119
ID: 566d4af7-3bb9-11e8-8864-060555473160
UDP Port: 65528
Network interfaces: 192.168.66.70 
P2P Interface tap3, HW Addr: 06:74:e4:90:2d:27, IP: 10.82.47.245
Proxies: 54.233.167.241:40622/20033 13.250.117.166:40622/20033 54.183.200.212:40622/20032 52.58.220.11:40622/20023 35.159.10.202:40622/20023 
Peers:
	--- ba4ef5fe-3bb4-11e8-8a43-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.82.47.2 06:bf:67:17:a2:c0
	Endpoint: 52.58.220.11:20016
	All Endpoints: 52.58.220.11:20016 35.159.10.202:20016 54.183.200.212:20018 54.233.167.241:20018 
	Endpoints pool: 62.138.16.134:52720 10.10.10.254:52720 172.30.64.252:52720 172.21.27.252:52720 172.18.221.251:52720 172.19.134.252:52720 172.16.166.252:52720 52.58.220.11:20016 35.159.10.202:20016 54.183.200.212:20018 54.233.167.241:20018 13.250.117.166:20018 
	--- End of ba4ef5fe-3bb4-11e8-8a43-060555473160 ---
	--- b591c30d-3bb4-11e8-805c-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.82.47.1 06:0e:40:ba:a0:1d
	Endpoint: 13.250.117.166:20003
	All Endpoints: 13.250.117.166:20003 
	Endpoints pool: 10.0.2.15:50150 192.168.1.211:50150 172.28.128.3:50150 10.10.10.254:50150 172.27.131.251:50150 172.22.35.252:50150 172.19.73.252:50150 172.18.221.247:50150 172.19.204.252:50150 172.19.134.251:50150 172.21.78.252:50150 96.246.161.207:50150 54.183.200.212:20003 52.58.220.11:20004 35.159.10.202:20004 54.233.167.241:20003 13.250.117.166:20003 
	--- End of b591c30d-3bb4-11e8-805c-060555473160 ---
Bootstrap nodes:
Hash: swarm-10d8ab1f-4eb8-4df2-8f4f-f4672e533d19
ID: 60aacd7e-3bb9-11e8-8bb6-060555473160
UDP Port: 60011
Network interfaces: 192.168.66.70 
P2P Interface tap0, HW Addr: 06:51:7e:3c:c4:2b, IP: 10.179.228.245
Proxies: 54.183.200.212:40622/20047 52.58.220.11:40622/20047 35.159.10.202:40622/20048 54.233.167.241:40622/20047 13.250.117.166:40622/20049 
Peers:
	--- 84c7e3d0-3bb8-11e8-87fd-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.179.228.2 06:4a:98:4a:c9:48
	Endpoint: 54.183.200.212:20037
	All Endpoints: 54.183.200.212:20037 52.58.220.11:20038 13.250.117.166:20038 
	Endpoints pool: 148.72.176.17:43068 172.31.245.252:43068 172.25.145.252:43068 172.18.221.250:43068 172.17.68.252:43068 172.30.64.250:43068 172.21.27.251:43068 10.10.10.254:43068 172.22.199.252:43068 172.28.216.250:43068 54.183.200.212:20037 52.58.220.11:20038 35.159.10.202:20038 54.233.167.241:20038 13.250.117.166:20038 
	--- End of 84c7e3d0-3bb8-11e8-87fd-060555473160 ---
	--- ba0517b0-3bb4-11e8-8a6a-060555473160 ---
	States: REQUESTING_PROXIES | UNKNOWN
	No IP assigned
	Endpoints pool: 62.138.16.134:42555 10.10.10.254:42555 172.30.64.252:42555 172.21.27.252:42555 172.18.221.251:42555 172.19.134.252:42555 172.16.166.252:42555 
	--- End of ba0517b0-3bb4-11e8-8a6a-060555473160 ---

Shahris-Air:~ shahrizadakarasulu$```

**Comment by crioto** [comment] 2018-04-16 10:41
Non-reproducable. There is no Subutai P2P in Application after installing. We are waiting for designer to develop a P2P icon that will be added to Applications.

**Comment by TerGunter** [comment] 2018-04-21 11:31
I installed two p2p on one PC, from website and CC. First one from website was appeared in the application, but not displayed in the CC. Second one from CC was appeared there, but not displayed in the applications.
p2p debug show me logs after install from CC
and then i installed p2p from website it doesn't initialized in CC and doesn't show p2p debug output. So i can't reproduce this problem properly @crioto

**Comment by TerGunter** [comment] 2018-04-27 06:39
Fixed on prod

**Comment by AlinaPenkina** [comment] 2018-04-27 06:40
Done.

**Closed by AlinaPenkina** 2018-04-27 06:40 UTC
Labels: Mac
